logging:
  level:
    org:
      springframework: info

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  messages:
    basename: messages
  security:
    user:
      name: "user"
      password: "824a0fa4"

management:
  endpoints:
    web:
      exposure:
        include: "*"